<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>testbucket-ntp-cli</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.53.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestBucket.Ntp.Core\TestBucket.Ntp.Core.csproj" />
  </ItemGroup>

</Project>
